name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: JY7B6DD
          ICON_FIRST: "#03102f"
          ICON_SECOND: "#1688bf"
          BACKGROUND_FIRST: "#006eff"
          BACKGROUND_SECOND: "#99cfff"
          LANG: "ja"
          # CARD_WIDTH: "400"
          # UPDATE_TIME: "true"
